### ISSUE TITLE
Fix naming of policies on policy management form

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#101]
- Width of the risk profile configuration form can be much bigger.  
- When clicking on a new policy to add, the button shows for example "add pricetolerance policy", those need to be renamed and capitalized "Add price tolerance policy"

**Comment by fubhy** [comment]
The manage policies page and other pages (shutdown, etc.) will be merged.

**Comment by fubhy** [comment]
https://github.com/avantgardefinance/interface/issues/103

**Comment by jennazenk** [comment]
Reopening because the second point is still valid
