### ISSUE TITLE
Add returnBatchToVault on fund shutdown.

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#102]
- Make sure that when the user clicks on "shut down fund", the first transaction triggered is `returnBatchToVault` (https://github.com/melonproject/protocol/blob/develop/src/fund/trading/Trading.sol#L332-L336) and then shut down. This way we ensure the manager always cleans up the state of the fund before shutting it down, leaving full redemption capabilities to investors. 

See on redeem.melon.fund how it's done

**Comment by fubhy** [comment]
This page will be merged with other administrative pages. https://github.com/avantgardefinance/interface/issues/103

The returnBatchToVault transaction needs to be added.
