### ISSUE TITLE
Add temporary indicator on fund's page

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#116]
After fund setup for "Configuring the risk profile" and  "first investment"

The indicator should appear on the fund's page for 24 hours after inception, if no risk profile as configured and no first investment was made. 

It should be in the form of an informative note: 

"Congratulations on deploying your on-chain fund. You can now **configure the risk profile of your fund** and **become your first investor**. " 

The two bolded parts should redirect respectively to policies management screen and invest screen

**Comment by fubhy** [comment]
@ishak-lm I don't see any new code for this, did you move this by accident?
