### ISSUE TITLE
Fix share price on fund's page

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#119]
Currently displayed 0 (probably data is not fetched) 

It works on the fund's list

**Comment by fubhy** [comment]
Fixed already yesterday. Were you on an old version?

**Comment by fubhy** [comment]
![Screenshot from 2020-01-08 11-47-08](https://user-images.githubusercontent.com/1172528/71972294-a8ba4f00-320c-11ea-8587-ad7740443549.png)
