### ISSUE TITLE
Footer labels

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#130]
- Protocol -> About 

- Maybe remove network/graph explorer ? What do you think @fubhy ? 

- "price feed " -> pricefeed

**Comment by fubhy** [comment]
I'd like to keep graph/network explorer until we are done. We regularly use it.

**Comment by jennazenk** [comment]
Ok we can remove it when it's release ready. 

@ishak-lm can you take care of the "price feed" to "pricefeed" change?

**Comment by fubhy** [comment]
Superseded by https://github.com/avantgardefinance/interface/issues/151
