### ISSUE TITLE
Kyber trading randomly fails on gas estimation 

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#158]
No more detail than "gas required exceeds allowance or always failing transaction". We need better error messages here, at least a validation on all the `require` of the called function  

I saw it happening over few pairs: DAI/MLN, DAI/REP, DAI/USDC, DAI/KNC, while some other pairs work without issue.

See screenshot
<img width="1677" alt="Capture d’écran 2020-01-13 à 08 21 03" src="https://user-images.githubusercontent.com/17808182/72250240-6ffaeb00-35fb-11ea-8df3-05dc65f168d1.png">

**Comment by fubhy** [comment]
This works now for everything except for DGX. I am not sure why DGX fails because it's definitely not a decimals issue (WBTC and USDC work despite also using non-18 decimals).

**Comment by jennazenk** [comment]
DGX is expected to fail, and that's why we are removing it from the next deployment file
