### ISSUE TITLE
Add 'balances' block on the wallet overview page

### ISSUE THREAD

**Issue by iherger** [avantgardefinance/interface#164]
I think it would be helpful for a user to have a subpage `Balances` on their wallet page. This should contain their `ETH` balance, and also the balance for any asset tokens, e.g. `MLN`, `KNC`, etc.

Currently, the user can see their `ETH` balance in the top right corner (the amount should be shown next as `Your wallet (13.5 ETH)`, I suggest). In order to see their `WETH` balance, the user has to go to the Wrap Ether page. And the balances of the other tokens are shown nowhere at the moment.

**Comment by fubhy** [comment]
This could also just be a block on the overview page of the wallet.

I also like the proposal to includ the ETH balance in the "your wallet" text in the header instead of having it as a separate item there.
