### ISSUE TITLE
Fund factsheet label change

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#175]
Change 

- [x] Gross asset value -> GAV (Gross Asset Value)
- [x] Net asset value -> NAV (Net Asset Value) 

add 

- [x] AUM (Assets Under Management)
- [x] Start of next performance fee period 
- [x] Return since inception 
- [x] Allowed exchanges
- [x] Annualized return 
- [x] Annual volatility 

(the last two @iherger would know better as he's done it for Monitoring)

**Comment by fubhy** [comment]
JFYI: I actually checked Wikipedia for the right spelling before I switched from AUM/GAV/NAV to the fully spelled out versions (granted, that's probably not a good source of correctness): 

https://en.wikipedia.org/wiki/Net_asset_value
https://en.wikipedia.org/wiki/Gross_asset_value
https://en.wikipedia.org/wiki/Assets_under_management

**Comment by jennazenk** [comment]
Thank you Sebastian for the very insightful wikipedia links. Please spell it as below: 

- [ ] Gross asset value -> GAV (Gross Asset Value)

- [ ]  Net asset value -> NAV (Net Asset Value)

 - [ ] AUM (Assets Under Management)

**Comment by fubhy** [comment]
Why the snark. That was a legit question.

**Comment by jennazenk** [comment]
What is the question exactly?

**Comment by fubhy** [comment]
So, as discussed: 

 Gross asset value -> GAV (Gross asset value)

 Net asset value -> NAV (Net asset value)

 AUM (Assets under management)

**Comment by iherger** [comment]
Implemented by #189
