### ISSUE TITLE
Invest form: if user has no weth add a small note to redirect him to wrapping eth 

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#176]
Currently not clear to the user that he has the ability to wrap ETH

**Comment by fubhy** [comment]
@jennazenk We should probably always show this message was a neutral information bar, even if the user already has WETH they might not know that we offer the wrapping service in our user interface.

What should the message be exactly? See https://github.com/avantgardefinance/interface/pull/179/files

**Comment by jennazenk** [comment]
Yes we can always show it when WETH is selected. 

Msg is: "Get WETH by wrapping your ether in the wallet section." (with a link to the wallet section)
