### ISSUE TITLE
Find a solution for 404 pages

### ISSUE THREAD

**Issue by fubhy** [avantgardefinance/interface#196]
Either we redirect to the front page in case of any 404 (easy) or we create a properly styled error page with a link/button to go back to the previous page / front page.

**Comment by fubhy** [comment]
For me, a redirect to the front page (use <Redirect> component) is fine for now. Let's add a TODO for a better 404 page later (E.g. "are you on the right network?!", etc.).

**Comment by ishak-lm** [comment]
The implementation of Redirect is done. Do we need to ask @beatrizbeato for the design of the 404 Page?
