### ISSUE TITLE
Transaction modal: display contract/method/parameters/gas estimate

### ISSUE THREAD

**Issue by iherger** [avantgardefinance/interface#198]
I think it would be nice for users if they could see the details of the transaction that they are going to execute in the transaction modal.

I was thinking about the following things:

- [ ] contract (name, address)
- [ ] method (name)
- [ ] parameters
- [x] gas estimation (some calls are quite expensive and I think it would be good to be upfront about this), both in ETH and in USD
- [x] amgu / incentive (already there in ETH, add USD)

Parts of this (contract/method/parameters) could go into a `Show Details` section, which is only displayed if the user toggles it.

**Comment by fubhy** [comment]
The USD prices should be shown in various other places in the frontend too. Can you create an issue to integrate the coinapi endpoint that we also use in monitoring?

**Comment by fubhy** [comment]
I think we should show all of this information straight on the modal (and not just behind a toggle) and also link e.g. the contract address to etherscan, etc.

**Comment by iherger** [comment]
Error reporting link
