### ISSUE TITLE
Blue alert messages: color definition 

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#203]
I think we need to find another color for those alert lessages, because the blue comes a bit ... out of the blue. 

I was thinking maybe we could put it in the same color as the logo ? 

Or otherwise it could just be on black/grey background. 

Any idea @beatrizbeato ?

**Comment by fubhy** [comment]
While we are doing that, we should however also check the color contrasts with the text.  Warning, success, etc. are not very readable atm. Maybe it's also just a positioning / border queston. Maybe it looks better if we had a border around those or so.

I don't think black would be a good solution. We have three differnet "kinds" of these notifications. Error / Warning, Neutral, Success. I don't like the current color palette for these either, but I don't think (full) black or (full) grey would be a good alternative. Maybe a bit less flashy colors (more greyish blue) could work.

**Comment by fubhy** [comment]
@jennazenk Let's just decide this on our own then. Can you play around a bit with the colors in the browser maybe and tell us what you think would match visually?

**Comment by jennazenk** [comment]
I vote for using the color of the logo, but with a bit of opacity not to be too agressive

**Comment by fubhy** [comment]
The color of the logo is dynamic and completely random. It's really hard to make sure that the text is still readable. Also, the color might turn red/green so it would look like a warning error. Furthermore, we have multiple different kinds of notifications: error / warning / neutral (this one) / success. We have to stick to a static color value for these and assign them according to the meaning of the notification message. Error = red-is, Warning = yellow-ish, Neutral = whatever I guess / currently blueish, success = greenish.

**Comment by jennazenk** [comment]
In that case my suggestion is to have it black text on white background, border with color of the logo

**Comment by iherger** [comment]
- [ ] Error, danger and success messages color
