### ISSUE TITLE
Colored number changes 

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#208]
- Return since inception / Annualized return : green or red depending if number is positive or negative

- Annual volatility: this should stay in black imho. Thoughts @iherger ?

<img width="399" alt="Capture d’écran 2020-01-16 à 16 58 16" src="https://user-images.githubusercontent.com/17808182/72540635-6a163b80-3881-11ea-8ae2-d839d3b79082.png">

**Comment by fubhy** [comment]
Whoops so Annual Volatility is not one of these "good/bad" (e.g. like daily change) value? I just added the colorization in a commit only a few minutes ago and assumed that it was the case for all 3 of these.

**Comment by jennazenk** [comment]
It is, but not in the same way as others and it is more subjective

**Comment by iherger** [comment]
Annual volatility should be black, indeed. It can only be zero or higher, and I don't think we want to define "good" or "bad" volatility.
