### ISSUE TITLE
Header changes

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#217]
- [x] Move MAINNET / FUND / WALLET buttons to the right-hand side

- [x] Add to the left-hand side: Melon Manager Interface 

- [x] Remove the eth balance 

- [x] Move the eth balance to the wallet section

- [x] Network: mainnet / kovan (as text) 

- [x] Log in button: right-hand side. If not logged in "Log in", if logged in, logo of the connection method 

- [x] Footer: Add network

**Comment by ishak-lm** [comment]
Add to the left-hand side: Melon Manager Interface:

We need a new version of the Logo because we can't work on this SVG version.
