### ISSUE TITLE
Investment history table: fix "Amount in ETH"

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#220]
- [x] Rename "Amount in ETH" to "Value in ETH"

- [x]  If investment was made in another token than WETH, the value in that column must be converted in ETH. So in screenshot below, that should be  19978 MLN * price ETH per MLN

<img width="1310" alt="Capture d’écran 2020-01-17 à 19 35 29" src="https://user-images.githubusercontent.com/17808182/72637365-6eb22100-3961-11ea-9016-360b42df0d9c.png">

- [x] "Shares price" -> Share price

- [x] "Shares" -> Number of shares

**Comment by iherger** [comment]
Something else on that table needs to be fixed: 

- [ ] the `Amount` value is not correct for assets with non-standard decimals (e.g. USDC).

**Comment by fubhy** [comment]
@iherger Good point. Let's do a string serach for `18` in the frontend to find all cases where we still do this wrong!
