### ISSUE TITLE
Trade page layout change 

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#272]
- [x] I would like to reposition the components so that the "Trading" component and "Portfolio holidngs" components are next to each other 

To make space for this we can: 

- [x] Reduce the white space between the orderbook columns 

- [x] Hide the "Price" and "Value" columns in portfolio holdings

**Comment by fubhy** [comment]
As discussed on Keybase, we'll instead move the holdings to the next row and put the liquidity provider trading interface next to the orderbook trading interface.

**Comment by jennazenk** [comment]
yes but this one was closed by a PR from @ishak-lm. We have another issue for the merging of Liquidity Pools and putting them in a separate component

**Comment by fubhy** [comment]
Yes I know I just closed it properly (was only marked as "review" before).
