### ISSUE TITLE
Add a swap icon for kyber & uniswap trading

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#274]
User should be able to swap base and quote asset. See example on screenshot from Kyberswap 

<img width="788" alt="Capture d’écran 2020-01-27 à 14 46 24" src="https://user-images.githubusercontent.com/17808182/73179495-d1e74480-4113-11ea-9063-7a68bac40782.png">

**Comment by fubhy** [comment]
We should've waited with this because on the merged liquidity provider form this works differently. We have to redo this now.
