### ISSUE TITLE
No way to return to main page on mobile

### ISSUE THREAD

**Issue by iherger** [avantgardefinance/interface#298]
On mobile, the `Melon Manager Interface` text/link in the header is not displayed (for lack of space). This currently leaves the user without a link to the main page.

Suggestions:
- link Melon logo to the main page for all screen sizes
- link Melon logo to the main page just in the case that the `Melon Manager Interface` text/link is not visible.
- show the left arrow on mobile (but not the `Melon Manager Interface` text), keeping it clickable.

**Comment by fubhy** [comment]
Yes, I think your second suggestion is nice: When on mobile, make the logo link to the front page instead of switchign colors (only have the color gimmick on desktop).
