### ISSUE TITLE
Inconsistency between exchanges shown in fund factsheet and exchanges ticked in admin page 

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#316]
In admin page if the ticked exchanges don't correspond with the exchanges actually already plugged into the fund; see screenshots attached 

<img width="511" alt="Capture d’écran 2020-02-05 à 08 36 14" src="https://user-images.githubusercontent.com/17808182/73846951-62e4ac80-47f3-11ea-853d-1931205fc872.png">

<img width="647" alt="Capture d’écran 2020-02-05 à 08 36 30" src="https://user-images.githubusercontent.com/17808182/73846887-46487480-47f3-11ea-8d4c-f41f7e888310.png">

**Comment by iherger** [comment]
This was due to lowercase addresses vs. checksum addresses, which are currently not used consistently.
