### ISSUE TITLE
Liquidity pools component fine-tuning 

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#335]
For sake of time, we dropped a few things last week on that component: 

- [ ] Swap arrow needs to be rotated 

- [ ] We need to find a way to add back the rate of each pool (maybe under the name of the pool, above the button, in small font?) 

Generally speaking, I think we can figure out an even better way to display all of this because I am not sure it is 100% clear to the user

**Comment by erin-koen** [comment]
![image](https://user-images.githubusercontent.com/46381469/74388150-9c578200-4dc8-11ea-8787-fe9eb2d00af4.png)
![image](https://user-images.githubusercontent.com/46381469/74388164-af6a5200-4dc8-11ea-8896-3acc050267cf.png)

**Comment by jennazenk** [comment]
I like both the kyber and uniswap way, with the token symbol in the input field. That being said, the difficulty for us is that we have different offers for the "to" quantity (uniswap/kyber/and eventually melon engine), and that's the hard part to visualize the different quote, without taking so much space like we're doing now. Thoughts @fubhy ?
