### ISSUE TITLE
Trying to add an exchange to a fund leads to a wrong error 

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#338]
Here, I am trying to add 0x v3, and the form validation seems to be wrong:

<img width="641" alt="Capture d’écran 2020-02-12 à 21 00 06" src="https://user-images.githubusercontent.com/17808182/74372315-b732f200-4dda-11ea-9f8b-b999e528a988.png">

**Comment by fubhy** [comment]
Good catch. Fixed.
