### ISSUE TITLE
Shorten post fund creation Twitter message 

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#347]
I'd reduce it to: 

I just deployed an on-chain fund to @ethereum, powered by @melonprotocol. My fund's name is XXX, it has a XXX% management fee and XXX% performance fee. Check out its full profile here: ${window.location.href}.

**Comment by fubhy** [comment]
@ishak-lm When you do that, please also reduce the amount of data that is fetched for the link.
