### ISSUE TITLE
Buy prices inverted on OrderBookTrading

### ISSUE THREAD

**Issue by iherger** [avantgardefinance/interface#356]
<img width="1185" alt="Screenshot 2020-02-18 at 14 48 17" src="https://user-images.githubusercontent.com/36133712/74741878-ea9fd180-525d-11ea-807c-0a857c79e377.png">

The buy prices USDC/WETH (top half) seem to be the inverse values of the correct values. 

These are also ZeroExV3 offers.

Oasisdex prices seem to be fine.

**Comment by fubhy** [comment]
I think I fixed this. Can you check again?
