### ISSUE TITLE
Use Participation.allowedAssets for invest form instead of fund holdings.

### ISSUE THREAD

**Issue by fubhy** [avantgardefinance/interface#81]

**Comment by fubhy** [comment]
Currently we use the holdings list of the fund to show the dropdown of the investment assets on the invest form. This is not correct. It is only possible to invest using the 'allowedAssets' from the Participation contract. I prepared a graphql field on the routes.participation type already (allowedAssets). This needs to be used for that. However, we still need to have the `sharePriceInAsset` value. So that has to be added somehow too. Ideally we would add that directly to a custom type 

```gql
type AllowedInvestmentAsset {
  token: TokenDefinition!
  price: BigNumber!
}

type Particionation {
  ...
  allowedAssets: [AllowedInvestmentAsset!]!;
  ...
}
```

and refactor the graphql resolver accordingly.

**Comment by iherger** [comment]
I implemented this in `melongql`, see https://github.com/melonproject/melongql/pull/1

Implemented in `interface` in https://github.com/avantgardefinance/interface/pull/84

However, in the current manager interface, `allowedAssets` is the same as `ownedAssets` (the fund factory automatically allows investments in all assets. 

So, we probably also need to implement a page for the manager to change the `allowedAssets` (calling `enableInvestment` and `disableInvestment` in the `Participation` contract.
