### ISSUE TITLE
Hovering on numbers displays the whole number with all the decimals 

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#87]
See on https://monitoring.melon.network/, hover on a number on a fund's page, and you'll see appear the entire number

**Comment by fubhy** [comment]
We should create a special reusable component for numbers in this case that we can use everywhere. Instead of formatting numbers in place we would use a component like `<FormatterNumber value={BigNumber} decimals={number} />` or so.

**Comment by fubhy** [comment]
Whoop, I created a follow-up for this now. #153
