### ISSUE TITLE
Transaction modal 

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#92]
- [x]  "GWEI" -> "gwei" 

- [x] "AMGU" -> Asset management gas 

- [x] For Asset management gas, display the entire number, expressed in eth

- [x]  "INCENTIVE" -> Incentive for request execution

- [x] For investment transaction, format incentive number to be expressed in eth not wei 
<img width="796" alt="Capture d’écran 2020-01-07 à 18 08 59" src="https://user-images.githubusercontent.com/17808182/71960784-4e6ebd80-320f-11ea-9ef1-b05a84247660.png">

You can remove the gas limit. It is not necessary, unless, we also show the total gas fee estimated that will be paid (that's what we used to do, but we can discuss if we want to have it also here) 

<img width="697" alt="Capture d’écran 2020-01-07 à 15 32 35" src="https://user-images.githubusercontent.com/17808182/71892722-1c078680-3163-11ea-9cc1-eb8c4a3807a4.png">

**Comment by iherger** [comment]
Fixed by https://github.com/avantgardefinance/interface/pull/141
