### ISSUE TITLE
Fund's page: on overview renaming

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#99]
Policies component

- [x]  "Policies" -> "Fund ruleset" 
- [x]  Parameters for userwhitelist ruleset should be N/A 
- [x]  UserWhitelist -> Investor whitelist 

Holdings component

- [x]  "Holdings" -> "Portfolio holdings" 
- [x] "Eth token" -> Wrapped ether 
- [x]  "ZeroX Protocol Token" -> 0x protocol token 
- [x]  "MakerDao" -> Maker token

**Comment by fubhy** [comment]
This needs to be done in the protocol. We use the names from the deployment output file.

**Comment by jennazenk** [comment]
Yes but you can have a mapping for displayed names

**Comment by fubhy** [comment]
I strongly disagree to have a second source of truth for token names. This makes it harder to maintain and also is a nice little possibility for inconsistencies. Instead, we should just "fix" the names in the deployment .json. That way we have a single source of truth.

**Comment by fubhy** [comment]
Just to clarify... The token names and other values are directly pulled from the environment across the entire app. That happens through melonjs. We would have to add special casing for such a mapping on every single form/screen/list that we display the names on.

**Comment by iherger** [comment]
Addressed in #129 

We are displaying the policy identifiers as stored in the contract. So changing `UserWhitelist` to something else would deviate from that.

**Comment by jennazenk** [comment]
Yes but we need to display it in a user friendly  and comprehensive way, so we can have a mapping in melon.js to make those names user interface friendly @iherger

**Comment by fubhy** [comment]
@iherger We can change this in the availableExchanges / availablePolicies / availableTokens lists in melonjs.
